name: Release

on:
  push:
    branches:
      - main

env:
  HUSKY: 0

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    concurrency: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "20.10.0"

      - name: Install yarn
        run: npm install -g yarn

      - name: Setup Cache and Install Dependencies
        uses: bahmutov/npm-install@v1.8.38

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1.4.5
        with:
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.CI_NPM_PUBLISH_TOKEN }}
