name: Validate

on: [pull_request]

jobs:
  build:
    name: Build, Test and Validate
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "20.10.0"
      - name: Install yarn
        run: npm install -g yarn
      - name: Setup Cache and Install Dependencies
        uses: bahmutov/npm-install@v1.8.38
      - name: Compile and Build
        run: yarn build
      - name: Run Tests
        run: yarn test
      - name: Validate
        run: yarn lint
